inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'tmp/**/*'

Bundler/OrderedGems:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false
